// Code generated by MockGen. DO NOT EDIT.
// Source: ./handler/repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	model "test-api/model"

	gomock "github.com/golang/mock/gomock"
)

// MockHandlerRepo is a mock of HandlerRepo interface.
type MockHandlerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerRepoMockRecorder
}

// MockHandlerRepoMockRecorder is the mock recorder for MockHandlerRepo.
type MockHandlerRepoMockRecorder struct {
	mock *MockHandlerRepo
}

// NewMockHandlerRepo creates a new mock instance.
func NewMockHandlerRepo(ctrl *gomock.Controller) *MockHandlerRepo {
	mock := &MockHandlerRepo{ctrl: ctrl}
	mock.recorder = &MockHandlerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlerRepo) EXPECT() *MockHandlerRepoMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockHandlerRepo) CreateProduct(p *model.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockHandlerRepoMockRecorder) CreateProduct(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockHandlerRepo)(nil).CreateProduct), p)
}

// DeleteProduct mocks base method.
func (m *MockHandlerRepo) DeleteProduct(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockHandlerRepoMockRecorder) DeleteProduct(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockHandlerRepo)(nil).DeleteProduct), id)
}

// FindProduct mocks base method.
func (m *MockHandlerRepo) FindProduct(filter model.ProductFilter) ([]model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProduct", filter)
	ret0, _ := ret[0].([]model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProduct indicates an expected call of FindProduct.
func (mr *MockHandlerRepoMockRecorder) FindProduct(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProduct", reflect.TypeOf((*MockHandlerRepo)(nil).FindProduct), filter)
}

// FindProductQueryParams mocks base method.
func (m *MockHandlerRepo) FindProductQueryParams(filter *model.ProductFilter2) ([]model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProductQueryParams", filter)
	ret0, _ := ret[0].([]model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProductQueryParams indicates an expected call of FindProductQueryParams.
func (mr *MockHandlerRepoMockRecorder) FindProductQueryParams(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProductQueryParams", reflect.TypeOf((*MockHandlerRepo)(nil).FindProductQueryParams), filter)
}

// GetAllProducts mocks base method.
func (m *MockHandlerRepo) GetAllProducts() ([]model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts")
	ret0, _ := ret[0].([]model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockHandlerRepoMockRecorder) GetAllProducts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockHandlerRepo)(nil).GetAllProducts))
}

// GetProductByID mocks base method.
func (m *MockHandlerRepo) GetProductByID(id int) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", id)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockHandlerRepoMockRecorder) GetProductByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockHandlerRepo)(nil).GetProductByID), id)
}

// UpdateProduct mocks base method.
func (m *MockHandlerRepo) UpdateProduct(id int, p *model.Product) (*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", id, p)
	ret0, _ := ret[0].(*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockHandlerRepoMockRecorder) UpdateProduct(id, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockHandlerRepo)(nil).UpdateProduct), id, p)
}
